first commit
ClevertecFrontendLab/sprint1-Kirik1714 pull request #1
Opened 2023-01-28 14:02 UTC by Kirik1714

2023-01-28 14:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674914881/content-window.png)

2023-01-28 15:02 UTC, Ivan6813 requested changes

2023-01-28 15:02 UTC, Ivan6813 commented on src/pages/book/book-page.jsx
> +
проверь размеры карточки при мобильном разрешении и сделай их в соответствии с макетом, проверь отступы и тогда должно пройти тест, который сейчас не проходит

2023-01-28 15:02 UTC, Ivan6813 commented on src/pages/main/main-page.jsx
> +  </div>
кнопка по макету прижата к низу карточки
![msedge_qS7aeSbbYa](https://user-images.githubusercontent.com/79784960/215273573-eca065c8-7a1b-4999-9ef0-9f18830002bc.png)

2023-01-28 17:14 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1674926084/content-window.png)

2023-01-29 15:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Kirik1714/1675004932/content-window.png)

2023-01-30 06:50 UTC, Ivan6813 approved these changes

2023-01-30 09:44 UTC, merged